// persons

export const SET_PERSONS_SUCCESS = 'SET_PERSONS_SUCCESS';
export const SET_PERSONS_FAILURE = 'SET_PERSONS_FAILURE';

export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE';

export const DELETE_PERSONS_SUCCESS = 'DELETE_PERSONS_SUCCESS';
export const DELETE_PERSONS_FAILURE = 'DELETE_PERSONS_FAILURE';

export const EDIT_PERSONS_SUCCESS = 'EDIT_PERSONS_SUCCESS';
export const EDIT_PERSONS_FAILURE = 'EDIT_PERSONS_FAILURE';

export const REFRESH_PERSON_SUCCESS = 'REFRESH_PERSON_SUCCESS';
export const REFRESH_PERSON_FAILURE = 'REFRESH_PERSON_FAILURE';

// records

export const SET_RECORDS_SUCCESS = 'SET_RECORDS_SUCCESS';
export const SET_RECORDS_FAILURE = 'SET_RECORDS_FAILURE';

export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';
export const ADD_RECORD_FAILURE = 'ADD_RECORD_FAILURE';

export const DELETE_RECORDS_SUCCESS = 'DELETE_RECORDS_SUCCESS';
export const DELETE_RECORDS_FAILURE = 'DELETE_RECORDS_FAILURE';

export const EDIT_RECORDS_SUCCESS = 'EDIT_RECORDS_SUCCESS';
export const EDIT_RECORDS_FAILURE = 'EDIT_RECORDS_FAILURE';
