// persons

export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_PERSONS_FAILURE = 'FETCH_PERSONS_FAILURE';

export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';

export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE';

export const DELETE_PERSONS_SUCCESS = 'DELETE_PERSONS_SUCCESS';
export const DELETE_PERSONS_FAILURE = 'DELETE_PERSONS_FAILURE';

export const EDIT_PERSONS_SUCCESS = 'EDIT_PERSONS_SUCCESS';
export const EDIT_PERSONS_FAILURE = 'EDIT_PERSONS_FAILURE';

// records

export const SET_RECORDS_SUCCESS = 'SET_RECORDS_SUCCESS';
export const SET_RECORDS_FAILURE = 'SET_RECORDS_FAILURE';

export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';
export const ADD_RECORD_FAILURE = 'ADD_RECORD_FAILURE';

export const DELETE_RECORDS_SUCCESS = 'DELETE_RECORDS_SUCCESS';
export const DELETE_RECORDS_FAILURE = 'DELETE_RECORDS_FAILURE';

export const EDIT_RECORDS_SUCCESS = 'EDIT_RECORDS_SUCCESS';
export const EDIT_RECORDS_FAILURE = 'EDIT_RECORDS_FAILURE';
