// app

export const TOGGLE_EDITING = 'TOGGLE_EDITING';
export const TOGGLE_SAVING = 'TOGGLE_SAVING';
export const TOGGLE_DELETING = 'TOGGLE_DELETING';

// persons

export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_PERSONS_FAILURE = 'FETCH_PERSONS_FAILURE';

export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_FAILURE = 'FETCH_PERSON_FAILURE';

export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const ADD_PERSON_FAILURE = 'ADD_PERSON_FAILURE';

export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILURE = 'DELETE_PERSON_FAILURE';

export const EDIT_PERSON_SUCCESS = 'EDIT_PERSON_SUCCESS';
export const EDIT_PERSON_FAILURE = 'EDIT_PERSON_FAILURE';

// records

export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';
export const ADD_RECORD_FAILURE = 'ADD_RECORD_FAILURE';

export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS';
export const DELETE_RECORD_FAILURE = 'DELETE_RECORD_FAILURE';

export const EDIT_RECORD_SUCCESS = 'EDIT_RECORD_SUCCESS';
export const EDIT_RECORD_FAILURE = 'EDIT_RECORD_FAILURE';
